import 'dart:convert';
import 'package:cryptography/cryptography.dart';

class CryptoUtils {
  // Hardcoded public key for verifying the CI/CD JS bundle
  // In production, this should match the key pair generated by your GitHub Actions
  static const String _publicKeyBase64 = 'PLACEHOLDER_PUBLIC_KEY_BASE64';

  /// Verifies the signature of the given data using Ed25519
  static Future<bool> verifySignature(String data, String signatureBase64) async {
    try {
      if (_publicKeyBase64 == 'PLACEHOLDER_PUBLIC_KEY_BASE64') {
        print('WARNING: Using placeholder public key. Signature verification bypassed.');
        return true; // Bypass during development if key isn't set
      }

      final ed25519 = Ed25519();
      final publicKeyBytes = base64Decode(_publicKeyBase64);
      final signatureBytes = base64Decode(signatureBase64);
      final dataBytes = utf8.encode(data);

      final publicKey = SimplePublicKey(publicKeyBytes, type: KeyPairType.ed25519);
      final signature = Signature(signatureBytes, publicKey: publicKey);

      return await ed25519.verify(dataBytes, signature: signature);
    } catch (e) {
      print('Signature verification failed: $e');
      return false;
    }
  }
}
